name: icon-theme-papirus
adopt-info: papirus
base: bare
build-base: core22
summary: Latest Complete Set of Papirus-Icons
description: |
  This snap provides the Papirus Icon Theme in a form that can be used
  by other snapped applications. It can be installed alongside the
  gtk-common-themes snap.
grade: stable
compression: lzo
confinement: strict

slots:
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/usr/share/icons/Papirus-Dark
        - $SNAP/usr/share/icons/Papirus
        - $SNAP/usr/share/icons/Papirus-Light
        - $SNAP/usr/share/icons/ePapirus-Dark
        - $SNAP/usr/share/icons/ePapirus

parts:      
  papirus:
    source: https://github.com/PapirusDevelopmentTeam/papirus-icon-theme.git
    plugin: make
    build-packages:
     - curl
     - build-essential
    override-pull: |
     craftctl default
     craftctl set version=$(git describe --tags --abbrev=0) 
     VER=$(git describe --tags --abbrev=0)
     curl -LO https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/archive/refs/tags/${VER}.tar.gz
    
